// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
	site: 'https://www.sanctum.run',
	vite: {
		server: {
			allowedHosts: ['sanctum.local'],
		},
	},
	integrations: [
		starlight({
			title: 'Le Sanctum',
			tagline: 'Your haus, wittily managed.',
			logo: {
				light: './src/assets/sanctum-logo-light.svg',
				dark: './src/assets/sanctum-logo-dark.svg',
				replacesTitle: false,
			},
			social: [
				{ icon: 'x.com', label: 'Follow @LeSanctum', href: 'https://x.com/LeSanctum' },
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/Ogilthorp3' },
			],
			customCss: ['./src/styles/custom.css'],
			disable404Route: true,
			head: [
				{
					tag: 'link',
					attrs: {
						rel: 'preconnect',
						href: 'https://fonts.googleapis.com',
					},
				},
				{
					tag: 'link',
					attrs: {
						rel: 'preconnect',
						href: 'https://fonts.gstatic.com',
						crossorigin: '',
					},
				},
				{
					tag: 'link',
					attrs: {
						rel: 'stylesheet',
						href: 'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,300;1,6..72,400&family=JetBrains+Mono:wght@300;400;500&display=swap',
					},
				},
			{
					tag: 'link',
					attrs: {
						rel: 'icon',
						type: 'image/svg+xml',
						href: '/favicon.svg',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image',
						content: 'https://www.sanctum.run/og-image.svg',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:width',
						content: '1200',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:height',
						content: '630',
					},
				},
				{
					tag: 'script',
					attrs: {
						src: '/easter-eggs.js',
						defer: true,
					},
				},
			],
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'What is Sanctum?', slug: 'getting-started/what-is-sanctum' },
						{ label: 'A Day in the Haus', slug: 'getting-started/a-day-in-the-haus' },
						{ label: 'Quick Start', slug: 'getting-started/quick-start' },
						{ label: 'Requirements', slug: 'getting-started/requirements' },
						{ label: 'Installation', slug: 'getting-started/installation' },
						{ label: 'First Run', slug: 'getting-started/first-run' },
						{ label: 'The First Hello', slug: 'getting-started/the-first-hello' },
						{ label: 'Firewalla Pairing', slug: 'getting-started/firewalla-pairing' },
						{ label: 'Single-NAT Setup', slug: 'getting-started/single-nat-setup' },
						{ label: 'HA Green Setup', slug: 'getting-started/ha-green-setup' },
						{ label: 'Pricing', slug: 'getting-started/pricing' },
					],
				},
				{
					label: 'Architecture',
					items: [
						{ label: 'Overview', slug: 'architecture/overview' },
						{ label: 'The Temple of the Kyber', slug: 'architecture/temple-of-the-kyber' },
						{ label: 'The Castellan', slug: 'architecture/the-castellan' },
						{ label: 'The Living Force', slug: 'architecture/living-force' },
						{ label: 'Emergence & Φ', slug: 'architecture/emergence-and-phi' },
						{ label: '(Neuro)diversity is Paramount', slug: 'architecture/neurodiversity-doctrine' },
						{ label: 'Chitti — The Fascial Layer', slug: 'architecture/chitti' },
						{ label: 'Force Flow', slug: 'architecture/force-flow' },
						{ label: 'Briefings', slug: 'architecture/briefings' },
						{ label: 'The Endocrine System', slug: 'architecture/endocrine-system' },
						{ label: 'The Chi', slug: 'architecture/chi' },
							{ label: 'Sanctum Firewalla', slug: 'architecture/sanctum-firewalla' },
						{ label: 'Council Router', slug: 'architecture/council-router' },
						{ label: 'Agents Architecture', slug: 'architecture/agents' },
						{ label: 'Jocasta MCP', slug: 'architecture/jocasta-mcp' },
						{ label: 'Sanctum Proxy', slug: 'architecture/proxy' },
						{ label: 'Sanctum Cloud Proxy', slug: 'architecture/sanctum-cloud-proxy' },
						{ label: 'Smart Router', slug: 'architecture/dynamic-model-routing' },
						{ label: 'How Hard to Think', slug: 'architecture/how-hard-to-think' },
						{ label: 'Smart Router Cathedral', slug: 'architecture/smart-router-cathedral' },
						{ label: 'Hybrid Sidecar', slug: 'architecture/hybrid-sidecar' },
						{ label: 'Sanctum MLX', slug: 'architecture/sanctum-mlx' },
						{ label: 'ds4max (Local Flash)', slug: 'architecture/ds4max' },
						{ label: 'Sanctum TTS', slug: 'architecture/sanctum-tts' },
						{ label: 'Sanctum Triage', slug: 'architecture/sanctum-triage' },
						{ label: 'LoRA in Rust', slug: 'architecture/lora-rust' },
						{ label: 'Turboquant KV Compression', slug: 'architecture/turboquant-kv-compression' },
						{ label: 'Turboquant Slice 4 Scoping', slug: 'architecture/turboquant-slice-4-scoping' },
						{ label: 'The Carmack Optimization', slug: 'architecture/carmack-optimization' },
						{ label: 'Eval Harness', slug: 'architecture/eval-harness' },
						{ label: 'The Champion Gate', slug: 'architecture/champion-gate' },
						{ label: 'Sanctum Olympics', slug: 'architecture/sanctum-olympics' },
						{ label: 'Model Comparison', slug: 'architecture/model-comparison' },
						{ label: 'Model Tournament', slug: 'architecture/model-tournament' },
						{ label: 'Training Lessons', slug: 'architecture/training-lessons' },
						{ label: 'Engineering Discipline', slug: 'architecture/engineering-discipline' },
						{ label: 'TCC Identity Anchors', slug: 'architecture/tcc-identity-anchors' },
						{ label: 'The Reliability Doctrine', slug: 'architecture/reliability-doctrine-v1' },
						{ label: 'Language Maturity', slug: 'architecture/language-maturity' },
						{ label: 'Config System', slug: 'architecture/config-system' },
						{ label: 'Beta Portability', slug: 'architecture/beta-portability' },
						{ label: 'Node Topology', slug: 'architecture/node-topology' },
						{ label: 'Services', slug: 'architecture/services' },
						{ label: 'Port Summary', slug: 'architecture/port-summary' },
						{ label: 'The Holocron Bridge (Yoda Chat)', slug: 'architecture/yoda-chat' },
						{ label: 'Holocron GUI', slug: 'architecture/holocron-gui' },
						{ label: 'Sanctum CRM', slug: 'architecture/crm-architecture' },
						{ label: 'Dealflow Intelligence', slug: 'architecture/dealflow-intelligence' },
						{ label: 'Screen Time', slug: 'architecture/screen-time' },
						{ label: 'The Kitchen Loop', slug: 'architecture/kitchen-loop' },
						{ label: 'R2D2 — Auto-Fix Supervisor', slug: 'architecture/r2d2' },
						{ label: 'The Resilience Doctrine', slug: 'architecture/resilience-doctrine' },
						{ label: 'The Parachute', slug: 'architecture/the-parachute' },
						{ label: 'Sanctum Continuity', slug: 'architecture/sanctum-continuity' },
						{ label: 'gitsync', slug: 'architecture/gitsync' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Dashboard', slug: 'guides/dashboard' },
						{ label: 'Holocron App', slug: 'guides/holocron-app' },
						{ label: 'Parent Unlock', slug: 'guides/parent-unlock' },
						{ label: 'Watchdog', slug: 'guides/watchdog' },
						{ label: 'Service Graph', slug: 'guides/service-graph' },
						{ label: 'Home Assistant', slug: 'guides/home-assistant' },
						{ label: 'AI Agents', slug: 'guides/agents' },
						{ label: 'Diagnosing Your Network', slug: 'guides/diagnosing-your-network' },
                                                { label: 'Agent Browser', slug: 'guides/agent-browser' },
						{ label: 'Autoresearch', slug: 'guides/autoresearch' },
						{ label: 'Gemma 4 Training', slug: 'guides/gemma4-training' },
						{ label: 'Sanctum MLX Beta Quickstart', slug: 'guides/sanctum-mlx-beta-quickstart' },
						{ label: 'Skills', slug: 'guides/skills' },
						{ label: 'Satellite Setup', slug: 'guides/satellite-setup' },
						{ label: 'Memory Vault', slug: 'guides/memory-vault' },
						{ label: 'Memory Service', slug: 'guides/memory' },
						{ label: 'Health Monitoring', slug: 'guides/health-monitoring' },
					],
				},
				{
					label: "Parents' Guide",
					items: [
						{ label: 'Overview', slug: 'parents-guide' },
						{ label: 'Block Now', slug: 'parents-guide/block-now' },
						{ label: 'More Time', slug: 'parents-guide/more-time' },
						{ label: 'Bedtime Now', slug: 'parents-guide/bedtime-now' },
						{ label: 'Homework Mode', slug: 'parents-guide/homework-mode' },
						{ label: 'Budgets', slug: 'parents-guide/budgets' },
						{ label: 'Schedules and Holidays', slug: 'parents-guide/schedules-and-holidays' },
						{ label: 'Troubleshooting', slug: 'parents-guide/troubleshooting' },
						{
							label: 'Mirrors',
							items: [
								{ label: 'Apple iOS', slug: 'parents-guide/mirrors/apple-ios' },
								{ label: 'Meta Quest', slug: 'parents-guide/mirrors/meta-quest' },
								{ label: 'Nintendo Switch', slug: 'parents-guide/mirrors/nintendo-switch' },
								{ label: 'Steam', slug: 'parents-guide/mirrors/steam' },
								{ label: 'Xbox & PlayStation', slug: 'parents-guide/mirrors/xbox-playstation' },
							],
						},
						{
							label: 'Québécois',
							items: [
								{ label: 'Guide des parents', slug: 'parents-guide/qc' },
								{ label: 'Bloque ça drette-là', slug: 'parents-guide/qc/block-now' },
								{ label: 'Dodo maintenant', slug: 'parents-guide/qc/bedtime-now' },
							],
						},
					],
				},
				{
					label: 'Agents',
					items: [
						{ label: 'Tommy \u2014 Guardian Spirit', slug: 'agents/tommy' },
						{ label: 'Wizard \u2014 The Human', slug: 'agents/wizard' },
						{ label: 'Yoda \u2014 Consigliere', slug: 'agents/yoda' },
						{ label: 'Windu \u2014 Security', slug: 'agents/windu' },
						{ label: 'Qui-Gon \u2014 Efficiency', slug: 'agents/quigon' },
						{ label: 'Cilghal \u2014 Health', slug: 'agents/cilghal' },
						{ label: 'Mundi \u2014 Finance', slug: 'agents/mundi' },
						{ label: 'Jocasta \u2014 CRM', slug: 'agents/jocasta' },
						{ label: 'Mothma \u2014 Operations', slug: 'agents/mothma' },
						{ label: 'Ahsoka \u2014 Satellite', slug: 'agents/ahsoka' },
						{ label: 'ds4-agent \u2014 Oracle', slug: 'agents/ds4-agent' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'instance.yaml', slug: 'reference/instance-yaml' },
						{ label: 'sanctum.yaml', slug: 'reference/sanctum-yaml' },
						{ label: 'Shell API', slug: 'reference/shell-api' },
						{ label: 'TypeScript API', slug: 'reference/typescript-api' },
						{ label: 'LaunchAgents', slug: 'reference/launchagents' },
						{ label: 'LaunchAgent Catalog', slug: 'reference/launchagents-catalog' },
						{ label: 'LaunchAgents Audit (2026-04-23)', slug: 'reference/launchagents-audit' },
						{ label: 'Service Inventory', slug: 'reference/service-inventory' },
						{ label: 'sanctum CLI (beta)', slug: 'reference/sanctum-cli' },
						{ label: 'CLI (operator surface)', slug: 'reference/cli' },
						{ label: 'signal-cli API', slug: 'reference/signal-cli-api' },
					],
				},
				{
					label: 'Operations',
					items: [
						{ label: 'The Arcs — five reading paths', slug: 'operations/the-arcs' },
						{ label: 'Living Force — Case Files & Field Notes', slug: 'operations/living-force-annex' },
						{
							label: 'Runbooks & Procedures',
							collapsed: true,
							items: [
								{ label: 'Verify', slug: 'operations/verify' },
								{ label: 'Backup & Restore', slug: 'operations/backup-restore' },
								{ label: 'Backup Dead-Man Switch', slug: 'operations/backup-deadman' },
								{ label: 'Secret Rotation', slug: 'operations/secret-rotation' },
								{ label: 'Upgrade Path', slug: 'operations/upgrade-path' },
								{ label: 'Screen Time Enforcement', slug: 'operations/screen-time-enforcement' },
								{ label: 'Sanctum Gateway Runbook', slug: 'operations/sanctum-gateway-runbook' },
								{ label: 'MBP Reboot Runbook', slug: 'operations/mbp-reboot-runbook' },
								{ label: 'mTLS Migration', slug: 'operations/mtls-migration' },
								{ label: 'Firewalla Gold Pro Migration', slug: 'operations/firewalla-gold-pro-migration' },
							],
						},
						{
							label: 'Doctrine & Policy',
							collapsed: true,
							items: [
								{ label: 'Security', slug: 'operations/security' },
								{ label: 'Privacy', slug: 'operations/privacy' },
								{ label: 'The Pressure Valve', slug: 'operations/pressure-valve' },
								{ label: 'Drift Sentinel', slug: 'operations/drift-sentinel' },
								{ label: 'Council Always-Alive', slug: 'operations/council-always-alive' },
								{ label: 'Yoda Warmth', slug: 'operations/yoda-warmth' },
								{ label: 'Device Identity', slug: 'operations/device-identity' },
								{ label: 'Shared Hardware Identity', slug: 'operations/device-identity-shared-hardware' },
								{ label: 'Activity Tracking', slug: 'operations/activity-tracking' },
								{ label: 'Naming', slug: 'operations/naming' },
							],
						},
						{
							label: 'State of the Haus',
							collapsed: true,
							items: [
								{ label: 'Operational State', slug: 'operations/operational-state' },
								{ label: 'Feature Status Matrix', slug: 'operations/feature-status-matrix' },
								{ label: 'Implementation Audit', slug: 'operations/implementation-audit' },
								{ label: 'Runtime Drift Audit', slug: 'operations/runtime-drift-audit' },
								{ label: 'Beta Readiness', slug: 'operations/beta-readiness' },
								{ label: 'Stability Window', slug: 'operations/stability-window' },
								{ label: 'Roadmap', slug: 'operations/roadmap' },
								{ label: 'Operational History', slug: 'operations/operational-history' },
							],
						},
						{
							label: 'Troubleshooting',
							collapsed: true,
							items: [
								{ label: 'Start Here', slug: 'operations/troubleshooting' },
								{ label: 'Service Troubleshooting', slug: 'operations/service-troubleshooting' },
								{ label: 'Signal Troubleshooting', slug: 'operations/signal-troubleshooting' },
								{ label: 'Tooling', slug: 'operations/tooling' },
								{ label: 'Report a Problem', link: 'https://github.com/Ogilthorp3/sanctum-cli/issues/new/choose', attrs: { target: '_blank' } },
							],
						},
						{
							label: 'Field Notes',
							collapsed: true,
							items: [
								{ label: '2026-08-04 — The Healer Learns a New Pipeline', slug: 'operations/2026-08-04-the-healer-learns-a-new-pipeline' },
								{ label: '2026-08-03 — The Haus Grows Senses', slug: 'operations/2026-08-03-the-haus-grows-senses' },
								{ label: '2026-08-02 — The Inbox Becomes a Ledger', slug: 'operations/2026-08-02-the-inbox-becomes-a-ledger' },
								{ label: '2026-08-01 — The Seal Only One Crate Carried', slug: 'operations/2026-08-01-the-seal-only-one-crate-carried' },
								{ label: '2026-07-31 — The Door That Does Not Refuse', slug: 'operations/2026-07-31-the-door-that-does-not-refuse' },
								{ label: '2026-07-31 — The Seven Brains', slug: 'operations/2026-07-31-the-seven-brains' },
								{ label: '2026-07-29 — The Key Baked Into the Wall', slug: 'operations/2026-07-29-the-key-baked-into-the-wall' },
								{ label: '2026-07-29 — The Firewall That Quarantined the Dishwasher', slug: 'operations/2026-07-29-the-firewall-that-quarantined-the-dishwasher' },
								{ label: '2026-07-29 — The Alarm Nobody Could Answer', slug: 'operations/2026-07-29-the-alarm-nobody-could-answer' },
								{ label: '2026-07-28 — The Dragon Earns Its Crown', slug: 'operations/2026-07-28-the-dragon-earns-its-crown' },
								{ label: '2026-07-28 — The Cache That Overwrote the Source', slug: 'operations/2026-07-28-the-cache-that-overwrote-the-source' },
        { label: '2026-07-26 — The Probe That Could Not Tell On Itself', slug: 'operations/2026-07-26-the-probe-that-could-not-tell-on-itself' },
								{ label: '2026-07-26 — The Ruler Was Broken, Not the Model', slug: 'operations/2026-07-26-the-ruler-was-broken' },
								{ label: '2026-07-26 — The Secret That Was Never Missing', slug: 'operations/2026-07-26-the-secret-that-was-never-missing' },
								{ label: '2026-07-26 — The Airgap That Forgot Itself', slug: 'operations/2026-07-26-the-airgap-that-forgot-itself' },
								{ label: '2026-07-26 — The Agent That Was Never Slow', slug: 'operations/2026-07-26-the-agent-that-was-never-slow' },
								{ label: '2026-07-26 — DRI Governance: The Council Picks Owners', slug: 'operations/2026-07-26-dri-governance-the-council-picks-owners' },
								{ label: '2026-07-25 — The Knobs That Outlived Their Reason', slug: 'operations/2026-07-25-the-knobs-that-outlived-their-reason' },
								{ label: '2026-07-24 — The Fleet Watches Itself', slug: 'operations/2026-07-24-the-fleet-watches-itself' },
								{ label: '2026-07-24 — The Cloud That Moved Out', slug: 'operations/2026-07-24-the-cloud-that-moved' },
								{ label: '2026-07-23 — The Name That Could Not Escape', slug: 'operations/2026-07-23-the-name-that-could-not-escape' },
								{ label: '2026-07-23 — The Block That Killed the Hub', slug: 'operations/2026-07-23-the-block-that-killed-the-hub' },
								{ label: '2026-07-21 — The Proxy Was Never the Problem', slug: 'operations/2026-07-21-the-proxy-was-never-the-problem' },
								{ label: '2026-07-20 — Fail Open, Fail Closed', slug: 'operations/2026-07-20-fail-open-fail-closed' },
								{ label: '2026-07-17 — The Pretender in the Pit', slug: 'operations/2026-07-17-the-pretender-in-the-pit' },
							{ label: '2026-07-16 — The reply that never left the bridge', slug: 'operations/2026-07-16-yoda-signal-silent-inbound' },
							{ label: '2026-07-16 — The Governor Edges', slug: 'operations/2026-07-16-the-governor-edges' },
								{ label: '2026-07-15 — proxyd, the CLI, and the Budget YAML', slug: 'operations/2026-07-15-proxyd-cli-budget-yaml' },
								{ label: '2026-07-14 — The Ladder With One Paid Rung', slug: 'operations/2026-07-14-the-ladder-with-one-paid-rung' },
								{ label: '2026-07-14 — The Device That Announces Itself', slug: 'operations/2026-07-14-the-device-that-announces-itself' },
								{ label: '2026-07-13 — The Maester Lost His Mind', slug: 'operations/2026-07-13-the-maester-lost-his-mind' },
								{ label: '2026-07-12 — The Panel Earns Its Place', slug: 'operations/2026-07-12-the-panel-earns-its-place' },
								{ label: '2026-07-11 — The Third Gate Opens', slug: 'operations/2026-07-11-the-third-gate-opens' },
								{ label: '2026-07-11 — The Doctor That Fainted at Every Diagnosis', slug: 'operations/2026-07-11-the-doctor-that-fainted-at-every-diagnosis' },
								{ label: '2026-07-11 — The Gateway Falls on Its Feet', slug: 'operations/2026-07-11-gateway-falls-on-its-feet' },
								{ label: '2026-07-11 — CI Comes Home', slug: 'operations/2026-07-11-ci-comes-home' },
								{ label: '2026-07-07 — The Fifth Guardian', slug: 'operations/2026-07-07-the-fifth-guardian' },
								{ label: '2026-07-07 — The Cathedral Routes by Need', slug: 'operations/2026-07-07-the-cathedral-routes-by-need' },
								{ label: '2026-07-06 — The Twin That Would Not Die', slug: 'operations/2026-07-06-the-twin-that-would-not-die' },
								{ label: '2026-07-06 — The Map Caught Up to the Territory', slug: 'operations/2026-07-06-the-map-caught-up-to-the-territory' },
								{ label: '2026-07-06 — The Ghost Leaves the Machine', slug: 'operations/2026-07-06-the-ghost-leaves-the-machine' },
								{ label: '2026-07-06 — The Dragonpit', slug: 'operations/2026-07-06-the-dragonpit' },
								{ label: '2026-07-06 — The Cathedral Holds Two Minds', slug: 'operations/2026-07-06-the-cathedral-holds-two-minds' },
								{ label: '2026-07-05 — The Understudy Takes the Stage', slug: 'operations/2026-07-05-the-understudy' },
								{ label: '2026-07-05 — No Haus Is An Island', slug: 'operations/2026-07-05-no-haus-is-an-island' },
								{ label: '2026-07-04 — The Claude Code Lane', slug: 'operations/2026-07-04-the-claude-code-lane' },
								{ label: '2026-07-03 — Verify Before You Fortify', slug: 'operations/2026-07-03-verify-before-you-fortify' },
								{ label: '2026-07-03 — The Flakes That Only Failed Under Load', slug: 'operations/2026-07-03-the-flakes-that-only-failed-under-load' },
								{ label: '2026-07-03 — The Doubly-Synced Git', slug: 'operations/2026-07-03-the-doubly-synced-git' },
								{ label: '2026-07-03 — Closing the Gaps', slug: 'operations/2026-07-03-closing-the-gaps' },
								{ label: '2026-07-03 — Clean for a Stranger', slug: 'operations/2026-07-03-clean-for-a-stranger' },
								{ label: "2026-07-02 — The Lights Go Local (and the Names That Wouldn't Stick)", slug: 'operations/2026-07-02-the-lights-go-local' },
								{ label: '2026-06-29 — The Form That Could Wipe the Haus', slug: 'operations/2026-06-29-the-form-that-could-wipe-the-house' },
							{ label: '2026-06-28 — Voice-Clone Recipe & Harness — Annex', slug: 'operations/2026-06-28-voice-clone-recipe-annex' },
							{ label: '2026-06-28 — The Franglais Turing Test', slug: 'operations/2026-06-28-the-franglais-turing-test' },
								{ label: '2026-06-27 — Cilghal Gets a Hero', slug: 'operations/2026-06-27-cilghal-gets-a-hero' },
							{ label: '2026-06-26 — The council’s independent-stack fallback — and the voice stack, settled', slug: 'operations/2026-06-26-council-fallback-and-voice' },
							{ label: '2026-06-25 — The gateway gets a doorman — proxyd’s api-key gate + a lint that won’t blink', slug: 'operations/2026-06-25-proxyd-api-key-gate' },
							{ label: '2026-06-24 — Closing the LAN — the loopback surface sweep', slug: 'operations/2026-06-24-loopback-surface-sweep' },
							{ label: '2026-06-23 — Command Center: the break-glass runbook', slug: 'operations/2026-06-23-command-center-recovery-runbook' },
							{ label: '2026-06-22 — The Day the Dashboard Learned Your Face', slug: 'operations/2026-06-22-passkey-mtls-hardening' },
								{ label: '2026-06-21 — ACL as Code', slug: 'operations/2026-06-21-acl-as-code' },
								{ label: '2026-06-20 — The Three-Seat Cathedral', slug: 'operations/2026-06-20-the-three-seat-cathedral' },
								{ label: '2026-06-20 — The Post-Quantum Vault', slug: 'operations/2026-06-20-the-post-quantum-vault' },
							{ label: '2026-06-19 — The Wheel That Wouldn’t Move', slug: 'operations/2026-06-19-the-wheel-that-wouldnt-move' },
								{ label: '2026-06-19 — The Speed Test That Cried Slow', slug: 'operations/2026-06-19-the-speed-test-that-cried-slow' },
								{ label: '2026-06-19 — The Jedi Who Knew Their Blast Radius', slug: 'operations/2026-06-19-the-jedi-who-knew-their-blast-radius' },
								{ label: '2026-06-15 — The Slash-One That Ate the LAN', slug: 'operations/2026-06-15-the-slash-one-that-ate-the-lan' },
								{ label: '2026-06-14 — The Reboot That Proved It', slug: 'operations/2026-06-14-the-reboot-that-proved-it' },
							{ label: '2026-06-14 — The Guards That Cried Wolf', slug: 'operations/2026-06-14-the-guards-that-cried-wolf' },
							{ label: '2026-06-13 — Subscription First', slug: 'operations/2026-06-13-subscription-first' },
								{ label: '2026-06-12 — Four Rungs, One Bet', slug: 'operations/2026-06-12-four-rungs-one-bet' },
								{ label: '2026-06-11 — The Ghost Wore Three Masks', slug: 'operations/2026-06-11-the-ghost-wore-three-masks' },
								{ label: '2026-06-08 — The SSH Key the Box No Longer Needs', slug: 'operations/2026-06-08-the-ssh-key-the-box-no-longer-needs' },
							{ label: '2026-06-08 — The Champion Gate Stack — Pipeline Architecture', slug: 'operations/2026-06-08-the-champion-gate-stack' },
								{ label: '2026-06-06 — The Gate Came Down', slug: 'operations/2026-06-06-the-gate-came-down' },
							{ label: '2026-06-06 — R2D2 Reads the Vault', slug: 'operations/2026-06-06-r2d2-reads-the-vault' },
								{ label: '2026-06-05 — The Eight-Item Sweep', slug: 'operations/2026-06-05-the-eight-item-sweep' },
								{ label: '2026-06-04 — The Memory Limit That Lived in the Container', slug: 'operations/2026-06-04-the-memory-limit-that-lived-in-the-container' },
							{ label: '2026-06-04 — The Aggregate Hid Two Weak Masters', slug: 'operations/2026-06-04-the-aggregate-hid-two-weak-masters' },
							{ label: '2026-06-02 — The Gate That Was Wrong For Two Weeks', slug: 'operations/2026-06-02-the-gate-that-was-wrong-for-two-weeks' },
							{ label: '2026-06-01 — The Workspace That Hid Two Stones', slug: 'operations/2026-06-01-the-workspace-that-hid-two-stones' },
							{ label: '2026-06-01 — R2D2 Stops Paging Itself', slug: 'operations/2026-06-01-r2d2-stops-paging-itself' },
							{ label: '2026-05-31 — The Night Yoda Got Bulletproof', slug: 'operations/2026-05-31-the-night-yoda-got-bulletproof' },
								{ label: '2026-05-28 — The Screen That Rewarded Forgetting', slug: 'operations/2026-05-28-the-screen-that-rewarded-forgetting' },
							{ label: '2026-05-24 — the gate that says no to memorization', slug: 'operations/2026-05-24-the-gate-that-says-no-to-memorization' },
							{ label: '2026-05-24 — the bandit picks first', slug: 'operations/2026-05-24-the-bandit-picks-first' },
							{ label: '2026-05-24 — msg-bus shipped, signal-cli quietly buried, OrbStack starts hidden at boot', slug: 'operations/2026-05-24-msg-bus-shipped' },
								{ label: '2026-05-23 — The Controller Quiet', slug: 'operations/2026-05-23-the-controller-quiet' },
								{ label: '2026-05-22 — The Installer the Friend Can Trust', slug: 'operations/2026-05-22-the-installer-the-friend-can-trust' },
							{ label: '2026-05-22 — The Champion Who Memorized the Exam', slug: 'operations/2026-05-22-the-champion-who-memorized-the-exam' },
							{ label: '2026-05-22 — The Cathedral Could Not Read Long', slug: 'operations/2026-05-22-the-cathedral-could-not-read-long' },
							{ label: '2026-05-22 — The Allow Button, Retired', slug: 'operations/2026-05-22-the-allow-button-retired' },
							{ label: '2026-05-21 — R2D2 Got Courage', slug: 'operations/2026-05-21-r2d2-got-courage' },
								{ label: '2026-05-20 — Three Things That Woke You', slug: 'operations/2026-05-20-three-things-that-woke-you' },
							{ label: '2026-05-19 — R2D2 Got Honest', slug: 'operations/2026-05-19-r2d2-got-honest' },
								{ label: '2026-05-18 — Windu Sweeps the Stuck', slug: 'operations/2026-05-18-windu-sweeps-the-stuck' },
								{ label: '2026-05-16 — The Port, the Renames, and the Orphan', slug: 'operations/2026-05-16-the-port-the-renames-and-the-orphan' },
								{ label: '2026-05-16 — The Door the Printer Opened', slug: 'operations/2026-05-16-the-door-the-printer-opened' },
							{ label: '2026-05-16 — Seventeen Days of Silent Failure', slug: 'operations/2026-05-16-seventeen-days-of-silent-failure' },
							{ label: '2026-05-16 — R2D2 Got Built And Found Eight Things', slug: 'operations/2026-05-16-r2d2-found-eight-things' },
								{ label: '2026-05-15 — Four Candles for the Cathedral', slug: 'operations/2026-05-15-four-candles-for-the-cathedral' },
								{ label: '2026-05-14 — The Cathedral Doubled Itself', slug: 'operations/2026-05-14-the-cathedral-doubled-itself' },
								{ label: '2026-05-13 — Wave 2 Doctrine Shipped', slug: 'operations/2026-05-13-wave-2-doctrine-shipped' },
								{ label: '2026-05-13 — The Adapter Found Its Home', slug: 'operations/2026-05-13-the-adapter-found-its-home' },
							{ label: '2026-05-12 — The Kernel Needed Two Tokens', slug: 'operations/2026-05-12-the-kernel-needed-two-tokens' },
							{ label: '2026-05-12 — The Fortnight In One Night', slug: 'operations/2026-05-12-the-fortnight-in-one-night' },
							{ label: '2026-05-11 — The Vault Spoke, Then I Misheard', slug: 'operations/2026-05-11-the-vault-spoke-then-i-misheard' },
								{ label: '2026-05-11 — The Shield and Its Shadow', slug: 'operations/2026-05-11-the-shield-and-its-shadow' },
							{ label: '2026-05-10 — The Vision Probe Lied', slug: 'operations/2026-05-10-the-vision-probe-lied' },
							{ label: '2026-05-10 — The Stress Test Caught It', slug: 'operations/2026-05-10-the-stress-test-caught-it' },
							{ label: '2026-05-10 — The Ladder That Heals Itself', slug: 'operations/2026-05-10-the-ladder-that-heals-itself' },
								{ label: '2026-05-10 — The Front Door', slug: 'operations/2026-05-10-the-front-door' },
							{ label: '2026-05-07 — The Reboot Reveals', slug: 'operations/2026-05-07-the-reboot-reveals' },
							{ label: '2026-05-07 — The Council Fell Silent', slug: 'operations/2026-05-07-the-council-fell-silent' },
							{ label: '2026-05-03 — The Cathedral Sees', slug: 'operations/2026-05-03-the-cathedral-sees' },
							{ label: '2026-05-02 — Honest Green', slug: 'operations/2026-05-02-honest-green' },
							{ label: '2026-05-01 — Asymmetric Doors', slug: 'operations/2026-05-01-asymmetric-doors' },
							{ label: '2026-04-30 — The Gates Held', slug: 'operations/2026-04-30-the-gates-held' },
							{ label: '2026-04-29 — First Breath', slug: 'operations/2026-04-29-first-breath' },
								{ label: '2026-04-28 — The Clean Stage', slug: 'operations/2026-04-28-the-clean-stage' },
								{ label: '2026-04-27 — The Vajrayogini Cut', slug: 'operations/2026-04-27-the-vajrayogini-cut' },
								{ label: '2026-04-27 — Two Gates, One Subscription', slug: 'operations/2026-04-27-claude-max-symmetry' },
								{ label: '2026-04-26 — Wisdom Informs Reflex', slug: 'operations/2026-04-26-wisdom-informs-reflex' },
								{ label: '2026-04-26 — Pressure-Valve Trilogy Redux', slug: 'operations/2026-04-26-valve-trilogy-redux' },
							{ label: '2026-04-26 — Borders and Edges', slug: 'operations/2026-04-26-borders-and-edges' },
								{ label: '2026-04-24 — Five Locks on the Voice Door', slug: 'operations/2026-04-24-sanctum-tts-hardening' },
								{ label: '2026-04-24 — OpenClaw Sunday Sync', slug: 'operations/2026-04-24-openclaw-sunday-sync' },
								{ label: '2026-04-24 — Every Jedi Answers to Their Name', slug: 'operations/2026-04-24-council-roll-call' },
								{ label: '2026-04-21 — The mTLS Day', slug: 'operations/2026-04-21-mtls-migration' },
								{ label: '2026-04-20 — The Pressure Valve Trilogy', slug: 'operations/2026-04-20-the-pressure-valve-trilogy' },
								{ label: '2026-04-20 — The A+ Roadmap Closes', slug: 'operations/2026-04-20-aplus-roadmap-closes' },
								{ label: '2026-04-19 — The Reasoner That Went Quiet', slug: 'operations/2026-04-19-council-mlx-silence' },
								{ label: '2026-04-18 — The Off-Catalogue Audit', slug: 'operations/2026-04-18-off-catalogue-audit' },
								{ label: '2026-04-17 — Full-Stack Health Sweep', slug: 'operations/2026-04-17-health-sweep' },
								{ label: '2026-04-15 — Living Force Manifest Deployment', slug: 'operations/2026-04-15-living-force-deployment' },
								{ label: '2026-04-07 — Provider Overhaul', slug: 'operations/2026-04-07-provider-overhaul' },
							],
						},
					],
				},
			],
		}),
	],
});
