// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
	site: 'https://www.sanctum.run',
	vite: {
		server: {
			allowedHosts: ['sanctum.local'],
		},
	},
	integrations: [
		starlight({
			title: 'Le Sanctum',
			tagline: 'Your haus, wittily managed.',
			logo: {
				light: './src/assets/sanctum-logo-light.svg',
				dark: './src/assets/sanctum-logo-dark.svg',
				replacesTitle: false,
			},
			social: [
				{ icon: 'x.com', label: 'Follow @LeSanctum', href: 'https://x.com/LeSanctum' },
				{ icon: 'github', label: 'GitHub', href: 'https://github.com/Ogilthorp3' },
			],
			customCss: ['./src/styles/custom.css'],
			disable404Route: true,
			head: [
				{
					tag: 'link',
					attrs: {
						rel: 'preconnect',
						href: 'https://fonts.googleapis.com',
					},
				},
				{
					tag: 'link',
					attrs: {
						rel: 'preconnect',
						href: 'https://fonts.gstatic.com',
						crossorigin: '',
					},
				},
				{
					tag: 'link',
					attrs: {
						rel: 'stylesheet',
						href: 'https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,300;0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,300;1,6..72,400&family=JetBrains+Mono:wght@300;400;500&display=swap',
					},
				},
			{
					tag: 'link',
					attrs: {
						rel: 'icon',
						type: 'image/svg+xml',
						href: '/favicon.svg',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image',
						content: 'https://www.sanctum.run/og-image.svg',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:width',
						content: '1200',
					},
				},
				{
					tag: 'meta',
					attrs: {
						property: 'og:image:height',
						content: '630',
					},
				},
				{
					tag: 'script',
					attrs: {
						src: '/easter-eggs.js',
						defer: true,
					},
				},
			],
			sidebar: [
				{
					label: 'Getting Started',
					items: [
						{ label: 'What is Sanctum?', slug: 'getting-started/what-is-sanctum' },
						{ label: 'Requirements', slug: 'getting-started/requirements' },
						{ label: 'Installation', slug: 'getting-started/installation' },
						{ label: 'First Run', slug: 'getting-started/first-run' },
						{ label: 'Pricing', slug: 'getting-started/pricing' },
					],
				},
				{
					label: 'Architecture',
					items: [
						{ label: 'Overview', slug: 'architecture/overview' },
						{ label: 'The Living Force', slug: 'architecture/living-force' },
						{ label: '(Neuro)diversity is Paramount', slug: 'architecture/neurodiversity-doctrine' },
						{ label: 'Chitti — The Fascial Layer', slug: 'architecture/chitti' },
						{ label: 'Force Flow', slug: 'architecture/force-flow' },
						{ label: 'Council Router', slug: 'architecture/council-router' },
						{ label: 'Agents Architecture', slug: 'architecture/agents' },
						{ label: 'Jocasta MCP', slug: 'architecture/jocasta-mcp' },
						{ label: 'Sanctum Proxy', slug: 'architecture/proxy' },
						{ label: 'Sanctum Cloud Proxy', slug: 'architecture/sanctum-cloud-proxy' },
						{ label: 'Smart Router', slug: 'architecture/dynamic-model-routing' },
						{ label: 'Smart Router Cathedral', slug: 'architecture/smart-router-cathedral' },
						{ label: 'Hybrid Sidecar', slug: 'architecture/hybrid-sidecar' },
						{ label: 'Sanctum MLX', slug: 'architecture/sanctum-mlx' },
						{ label: 'Sanctum TTS', slug: 'architecture/sanctum-tts' },
						{ label: 'Sanctum Triage', slug: 'architecture/sanctum-triage' },
						{ label: 'LoRA in Rust', slug: 'architecture/lora-rust' },
						{ label: 'Turboquant KV Compression', slug: 'architecture/turboquant-kv-compression' },
						{ label: 'Turboquant Slice 4 Scoping', slug: 'architecture/turboquant-slice-4-scoping' },
						{ label: 'The Carmack Optimization', slug: 'architecture/carmack-optimization' },
						{ label: 'Eval Harness', slug: 'architecture/eval-harness' },
						{ label: 'Sanctum Olympics', slug: 'architecture/sanctum-olympics' },
						{ label: 'Model Comparison', slug: 'architecture/model-comparison' },
						{ label: 'Model Tournament', slug: 'architecture/model-tournament' },
						{ label: 'Training Lessons', slug: 'architecture/training-lessons' },
						{ label: 'Engineering Discipline', slug: 'architecture/engineering-discipline' },
						{ label: 'The Reliability Doctrine', slug: 'architecture/reliability-doctrine-v1' },
						{ label: 'Language Maturity', slug: 'architecture/language-maturity' },
						{ label: 'Config System', slug: 'architecture/config-system' },
						{ label: 'Node Topology', slug: 'architecture/node-topology' },
						{ label: 'Services', slug: 'architecture/services' },
						{ label: 'The Holocron Bridge (Yoda Chat)', slug: 'architecture/yoda-chat' },
						{ label: 'Screen Time', slug: 'architecture/screen-time' },
						{ label: 'The Kitchen Loop', slug: 'architecture/kitchen-loop' },
					],
				},
				{
					label: 'Guides',
					items: [
						{ label: 'Dashboard', slug: 'guides/dashboard' },
						{ label: 'Holocron App', slug: 'guides/holocron-app' },
						{ label: 'Watchdog', slug: 'guides/watchdog' },
						{ label: 'Service Graph', slug: 'guides/service-graph' },
						{ label: 'Home Assistant', slug: 'guides/home-assistant' },
						{ label: 'AI Agents', slug: 'guides/agents' },
                                                { label: 'Agent Browser', slug: 'guides/agent-browser' },
						{ label: 'Autoresearch', slug: 'guides/autoresearch' },
						{ label: 'Gemma 4 Training', slug: 'guides/gemma4-training' },
						{ label: 'Skills', slug: 'guides/skills' },
						{ label: 'Satellite Setup', slug: 'guides/satellite-setup' },
						{ label: 'Memory Vault', slug: 'guides/memory-vault' },
						{ label: 'Memory Service', slug: 'guides/memory' },
						{ label: 'Health Monitoring', slug: 'guides/health-monitoring' },
					],
				},
				{
					label: 'Agents',
					items: [
						{ label: 'Tommy \u2014 Guardian Spirit', slug: 'agents/tommy' },
						{ label: 'Yoda \u2014 Consigliere', slug: 'agents/yoda' },
						{ label: 'Windu \u2014 Security', slug: 'agents/windu' },
						{ label: 'Qui-Gon \u2014 Efficiency', slug: 'agents/quigon' },
						{ label: 'Cilghal \u2014 Health', slug: 'agents/cilghal' },
						{ label: 'Mundi \u2014 Finance', slug: 'agents/mundi' },
						{ label: 'Jocasta \u2014 CRM', slug: 'agents/jocasta' },
						{ label: 'Mothma \u2014 Operations', slug: 'agents/mothma' },
						{ label: 'Ahsoka \u2014 Satellite', slug: 'agents/ahsoka' },
					],
				},
				{
					label: 'Reference',
					items: [
						{ label: 'instance.yaml', slug: 'reference/instance-yaml' },
						{ label: 'Shell API', slug: 'reference/shell-api' },
						{ label: 'TypeScript API', slug: 'reference/typescript-api' },
						{ label: 'LaunchAgents', slug: 'reference/launchagents' },
						{ label: 'LaunchAgents Audit (2026-04-23)', slug: 'reference/launchagents-audit' },
						{ label: 'CLI', slug: 'reference/cli' },
						{ label: 'signal-cli API', slug: 'reference/signal-cli-api' },
					],
				},
				{
					label: 'Operations',
					items: [
						{ label: 'Backup & Restore', slug: 'operations/backup-restore' },
						{ label: 'Pressure Valve', slug: 'operations/pressure-valve' },
						{ label: 'mTLS Migration', slug: 'operations/mtls-migration' },
						{ label: 'Troubleshooting', slug: 'operations/troubleshooting' },
						{ label: 'Security', slug: 'operations/security' },
						{ label: 'Secret Rotation', slug: 'operations/secret-rotation' },
						{ label: 'Tooling', slug: 'operations/tooling' },
						{ label: 'Verify', slug: 'operations/verify' },
						{ label: 'Upgrade Path', slug: 'operations/upgrade-path' },
						{ label: 'Operational State', slug: 'operations/operational-state' },
						{ label: 'Implementation Audit', slug: 'operations/implementation-audit' },
						{ label: 'Feature Status Matrix', slug: 'operations/feature-status-matrix' },
						{ label: 'Runtime Drift Audit', slug: 'operations/runtime-drift-audit' },
						{ label: 'Drift Sentinel', slug: 'operations/drift-sentinel' },
						{ label: 'Operational History', slug: 'operations/operational-history' },
						{ label: 'Stability Window', slug: 'operations/stability-window' },
						{ label: 'Roadmap', slug: 'operations/roadmap' },
						{ label: 'Council Always-Alive', slug: 'operations/council-always-alive' },
						{ label: 'Activity Tracking', slug: 'operations/activity-tracking' },
						{ label: 'Screen Time Enforcement', slug: 'operations/screen-time-enforcement' },
						{ label: 'MBP Reboot Runbook', slug: 'operations/mbp-reboot-runbook' },
						{ label: 'Firewalla Gold Pro Migration', slug: 'operations/firewalla-gold-pro-migration' },
						{
							label: 'Field Notes',
							collapsed: true,
							items: [
								{ label: '2026-04-28 — The Clean Stage', slug: 'operations/2026-04-28-the-clean-stage' },
								{ label: '2026-04-27 — The Vajrayogini Cut', slug: 'operations/2026-04-27-the-vajrayogini-cut' },
								{ label: '2026-04-27 — Two Gates, One Subscription', slug: 'operations/2026-04-27-claude-max-symmetry' },
								{ label: '2026-04-26 — Pressure-Valve Trilogy Redux', slug: 'operations/2026-04-26-valve-trilogy-redux' },
								{ label: '2026-04-26 — Wisdom Informs Reflex', slug: 'operations/2026-04-26-wisdom-informs-reflex' },
								{ label: '2026-04-24 — Five Locks on the Voice Door', slug: 'operations/2026-04-24-sanctum-tts-hardening' },
								{ label: '2026-04-24 — Every Jedi Answers to Their Name', slug: 'operations/2026-04-24-council-roll-call' },
								{ label: '2026-04-21 — The mTLS Day', slug: 'operations/2026-04-21-mtls-migration' },
								{ label: '2026-04-20 — The Pressure Valve Trilogy', slug: 'operations/2026-04-20-the-pressure-valve-trilogy' },
								{ label: '2026-04-20 — The A+ Roadmap Closes', slug: 'operations/2026-04-20-aplus-roadmap-closes' },
								{ label: '2026-04-19 — The Reasoner That Went Quiet', slug: 'operations/2026-04-19-council-mlx-silence' },
								{ label: '2026-04-18 — The Off-Catalogue Audit', slug: 'operations/2026-04-18-off-catalogue-audit' },
								{ label: '2026-04-17 — Full-Stack Health Sweep', slug: 'operations/2026-04-17-health-sweep' },
								{ label: '2026-04-15 — Living Force Manifest Deployment', slug: 'operations/2026-04-15-living-force-deployment' },
								{ label: '2026-04-07 — Provider Overhaul', slug: 'operations/2026-04-07-provider-overhaul' },
							],
						},
					],
				},
			],
		}),
	],
});
